# Generated by Django 5.1.3 on 2024-12-16 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_carbrand_carmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images_str', models.TextField(blank=True, null=True)),
                ('full_title', models.CharField(blank=True, max_length=256, null=True)),
                ('price_text', models.CharField(blank=True, max_length=256, null=True)),
                ('description_params_str', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=256, null=True)),
                ('description_text', models.TextField(blank=True, null=True)),
                ('main_url', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
