# Generated by Django 5.1.3 on 2024-12-16 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_allcar'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcar',
            name='data_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
