# Generated by Django 5.1.3 on 2024-12-18 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_allcar_detecsia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbrand',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
