# Generated by Django 5.1.3 on 2024-12-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_alter_carbrand_name_alter_carmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
