# Generated by Django 5.1.3 on 2024-12-18 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_alter_carmodel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allcar',
            name='carbrand',
        ),
        migrations.RemoveField(
            model_name='allcar',
            name='carmodel',
        ),
    ]
