# Generated by Django 5.1.3 on 2024-12-18 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_remove_allcar_carbrand_remove_allcar_carmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcar',
            name='carbrand',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='allcar',
            name='carmodel',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
